<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        /*
        1. Promise 构造函数: Promise (excutor) {}
        excutor 函数: 同步执行 (resolve, reject) => {}   执行函数
        resolve 函数: 内部定义成功时我们调用的函数 value => {}
        reject 函数: 内部定义失败时我们调用的函数 reason => {}
        说明: excutor 会在 Promise 内部立即同步回调,异步操作在执行器中执行

        2. Promise.prototype.then 方法: (onResolved, onRejected) => {}
        onResolved 函数: 成功的回调函数 (value) => {}
        onRejected 函数: 失败的回调函数 (reason) => {}
        说明: 指定用于得到成功 value 的成功回调和用于得到失败 reason 的失败回调
        返回一个新的 promise 对象

        3. Promise.prototype.catch 方法: (onRejected) => {}
        onRejected 函数: 失败的回调函数 (reason) => {}
        说明: then()的语法糖, 相当于: then(undefined, onRejected)
        
        4. Promise.resolve 方法: (value) => {}
        value: 成功的数据或 promise 对象
        说明: 返回一个成功/失败的 promise 对象

        5. Promise.reject 方法: (reason) => {}
        reason: 失败的原因
        说明: 返回一个失败的 promise 对象

        6. Promise.all 方法: (promises) => {}
        promises: 包含 n 个 promise 的数组
        说明: 返回一个新的 promise, 只有所有的 promise 都成功才成功, 只要有一
        个失败了就直接失败

        7. Promise.race 方法: (promises) => {}
        promises: 包含 n 个 promise 的数组
        说明: 返回一个新的 promise, 第一个完成的 promise 的结果状态就是最终的
        结果状态
*/

        new Promise((resolve, reject) => {
            setTimeout(function () {
                // resolve('成功的数据')
                reject('失败的数据')
            }, 1000)
        }).then(        //成功
            value => {
                console.log('onResolved()1', value)
            }
        ).catch(
            reason => { //失败
                console.log('onRejected()1', reason);
            }
        )

        //产生一个成功值为1的promise对象
        const p1 = new Promise((resolve, reject) => {
            setTimeout(function () {
                resolve(1)
            }, 100)
        })
        //产生一个成功值为2的promise对象  语法糖
        const p2 = Promise.resolve(2)
        //产生一个失败值为3的promise对象
        const p3 = Promise.reject(3)

        p1.then(value => { console.log(value) })
        p2.then(value => { console.log(value) })
        p3.catch(reason => { console.log(reason) })


        // const pAll = Promise.all([p1, p2, p3])
        const pAll = Promise.all([p1, p2])
        pAll.then(
            values => {
                console.log('all onResolved()', values);
            },
            reason => {
                console.log('all onRejected()', reason);
            }
        )

        const pRace = Promise.race([p1, p2, p3])
        //const pRace = Promise.race([p3,p2,p1])
        pRace.then(
            value => {
                console.log('race onResolved()', value);
            },
            reason => {
                console.log('race onRejected()', reason);
            }
        )
    </script>
</body>

</html>